name: Upload Python Package to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
environment:
  name: pypi
  url: https://pypi.org/p/realit-singer-python
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@fb9fc6a4e67ca27a7a76b17bbf90be83c2d3c716
